### ISSUE TITLE
Unevalizing the javascript programs does not give information about its sucess

### ISSUE THREAD

**Issue by ankur-1989** [cs-au-dk/TAJS#12]
Hi Team,

As part of my research, I was using TAJS and used its option -uneval. As mentioned in the paper Remedying the Eval that men do, it is to uneval the eval functions through different techniques. But when I run this on projects it does not give any such information if it was successful in unevalizing the eval function. Could you please help me in this? How can I get this information?

Thanks & Regards,
Ankur

**Comment by amoeller** [comment]
Try using the option `-eval-statistics` (together with `-uneval`).

**Comment by ankur-1989** [comment]
Hello Sir,
Thank you for the information. I tried the option, but it gives only the following fields without data -

Use of eval/innerHTML
 Constant eval'ed strings:
 Constant innerHTML strings:
 Source locations with maybe values for eval:

 Source locations with maybe values for innerHTML:
and for some of the sliced projects given in the Unevalizer benchmark, it gives the error 
exception in thread "main" java.lang.Error: Expected children to be strings

Thanks and Regards,
Ankur Gupta

**Comment by amoeller** [comment]
Please email amoeller@cs.au.dk instead of using the github issue tracker for such questions.
