### ISSUE TITLE
Error: Can't find ts-spec-reader directory!?

### ISSUE THREAD

**Issue by aliahsan07** [cs-au-dk/TAJS#14]
When I run TAJS with -type-filtering flag I get the error, that I can't find the ts-spec-reader directory. What am I missing?

**Comment by amoeller** [comment]
It should be in 'extras'. Did you download the sub-modules, using for example `git submodule update --init --recursive`?
Please note that type filtering is an experimental feature that is not complete yet.

**Comment by aliahsan07** [comment]
I did. The rest of the flags worked fine. Can't make this one work

**Comment by amoeller** [comment]
Did you also add
```
tajs = <PATH TO TAJS DIRECTORY>
```
to tajs.properties?

(Again, don't expect too much of this experimental feature.)

**Comment by aliahsan07** [comment]
thank you. 

I do have one analysis related question. What's the expected time of running tajs on a simple jquery program and running it with lets say determinacy flag?

**Comment by amoeller** [comment]
It varies a lot - see http://cs.au.dk/~amoeller/papers/tajsvr/ and http://cs.au.dk/~amoeller/papers/jquery/.
