### ISSUE TITLE
Abiliity to analyze projects (multiple js files with inter-procedural flow)

### ISSUE THREAD

**Issue by conikeec** [cs-au-dk/TAJS#15]
Upon a quick glance at readme, it was evident that the analysis is limited to only one file at a time

`java -jar dist/tajs-all.jar test-resources/src/google/richards.js
`
Is it possible to analyze an entire project (comprised of one or more files with inter procedural flow between them) 
For example
`java -jar dist/tajs-all.jar test-resources/nodegoat
`
for
https://github.com/OWASP/NodeGoat

If the project supports inter-procedural flow, I am happy to add a patch to accept a folder (to process all files) rather than an individual file.

**Comment by amoeller** [comment]
TAJS is a whole-program analysis, so it doesn't make sense to analyze the individual files. For client-side JavaScript, TAJS automatically loads the .js files linked from the given .html file (example: `java -jar dist/tajs-all.jar test-resources/src/chromeexperiments/3ddemo.html`). Support for server-side JavaScript (Node.js) is under development - NodeGoat is one of the case studies we use to drive that development - but it's not yet ready for release.
