### ISSUE TITLE
Null in dynamic property read (Pointer Analysis)

### ISSUE THREAD

**Issue by aliahsan07** [cs-au-dk/TAJS#17]
I'm running this example:
```
var src = {
  alpha: 1,
  beta: "testing",
  gamma: new Boolean(true),
};

var dest = {};
for (var prop in src) {
  dest[prop] = src[prop];
}
```
with show-variable-info flag and I get this:

![image](https://user-images.githubusercontent.com/13451316/78529114-9073b500-77a6-11ea-82a4-8235cdcb723b.png)

It seems to be that src.prop is named as null. Building a pointer analysis wrapper on top of tajs and this null makes querying a pointer harder.

**Comment by amoeller** [comment]
The null value appears because of the for-in loop and the dynamic property accesses. Null values are usually ignored by pointer analyses anyway.

**Comment by aliahsan07** [comment]
are you saying generally in pointer analysis we're not interested in finding points to set of src.prop?

**Comment by amoeller** [comment]
I'm saying that a spurious null value is usually not critical.
