### ISSUE TITLE
TAJS Plugin is blank and cannot be installed

### ISSUE THREAD

**Issue by JohnCheeKinChow** [cs-au-dk/TAJS#21]
Hi, 
I want to install TAJS on my eclipse but it is blank and cannot be installed anymore. 

Can someone help me out? 
Thanks a lot

**Comment by amoeller** [comment]
Sorry, the Eclipse plugin hasn't been updated for some time, so try the command-line version instead.

**Comment by JohnCheeKinChow** [comment]
Where can I find the command-line version?

**Comment by amoeller** [comment]
https://github.com/cs-au-dk/TAJS :-)

**Comment by JohnCheeKinChow** [comment]
Hi, thanks again, it worked. But I want to make call graphs but. that part still doesn't work.
I got this:

> java -callgraph dist/tajs-all.jar test-resources/src/chromeexperiments/3ddemo.html
Unrecognized option: -callgraph
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

I am probably still doing something wrong but don't know what

**Comment by amoeller** [comment]
Run it like this:
```
java -jar dist/tajs-all.jar -callgraph test-resources/src/chromeexperiments/3ddemo.html
```
And please contact me on amoeller@cs.au.dk instead of using github issue tracking for such questions :-)
