### ISSUE TITLE
[graphviz Question]How do you prefer to view .dot files?

### ISSUE THREAD

**Issue by KevinHock** [cs-au-dk/TAJS#9]
I've come across this in my own projects, maybe graphviz just sucks, but trying to view even the smallest files flowgraphs in .ps form e.g. `dot -Tps out/flowgraphs/initial.dot -o out/initial.ps` just gets cut off in any viewer I try.

Any suggestions on how to view them better?

Thanks for making TAJS, it's a great project!

**Comment by KevinHock** [comment]
Hmm I found `sfdp -x -Goverlap=scale -Tpng out/flowgraphs/initial.dot > out/TEST.png` works much better, still curious what you prefer though :)

**Comment by esbena** [comment]
I use the xdot program (on Ubuntu), it operates directly on the dot file instead of an image file.

**Comment by KevinHock** [comment]
Thanks 👍
